language: python
cache: pip
dist: xenial
python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - bash ./build_judy.sh
  - cd tests
  - ./compile.sh
  - cd ..
  - "pip install -r test-requirements.txt"

  - /bin/sh ./sh_build
  - gcc test.c -B./judy-1.0.5/src -Bstatic -lJudy
  - cd ../..
  - "pip install ."
  - "pip install -r test-requirements.txt"

script:
  - cd tests
  - ./a.out --unit-test-32
  - ./a.out --unit-test-64
  - cd ..
  - trial tests.python_api
