language: python
cache: pip
dist: xenial

os:
  - linux

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - bash ./build_judy.sh
  - cd tests
  - ./compile.sh
  - cd ..
  - pip install -r test-requirements.txt
  - python setup.py install

script:
  - cd tests
  - ./a.out --unit-test-32
  - ./a.out --unit-test-64
  - cd ..
  - PYTHONPATH=`pwd` trial tests.python_api
