language: python
python:
  - "2.6"
  - "2.7"

install:
  - "pip install ."
  - "pip install -r test-requirements.txt"
  - "(cd judy-1.0.5/src; COPT='-DJU_64BIT -O2 -fPIC -fno-strict-aliasing -fno-aggressive-loop-optimizations' sh ./sh_build)'

script:
  - "trial test.python_api"